name: CommunalAction
version: 1.2.2
author: Perotin
main: me.perotin.communalaction.CommunalAction
api-version: 1.14
commands:
   communalaction:
      usage: /communalaction <player>
      aliases: [ca, votep, votepunish]
      permission: communalaction.use