# Welcome to Communal Action's configuration.yml file!
# If you need any assistance, I am very reachable over Spigot!


# must be a multiple of 9, size of the inventory shown when doing /ca
inventory-size: 27

# name of the inventory
inventory-title: "Chose a punishment for $player$!"


# WARNING: This is where the core configurations of Communal Action come into play! Bear with me here.
# There are a few ways for Communal Action to decide when a vote should end
# The first is after a certain amount of votes is reached (i/e 5 votes and action takes place)
# The second is that a % of the online players have voted (i/e 50% of the server voted)

# So after reading the two choices above, how do you configure it to your liking?
# If you want it to use percentages, you would do '50%'. Make sure to include the percentage sign!
# If you want it to go by player count only, then just include the number i/e '5' players
# The command portion is the command that you want Communal Action to run when voted
# The broadcast option is if the plugin should broadcast to the entire server than <player> is being voted to be <muted/jailed/kicked>

# Currently the plugin is very one-dimensional in that players can only jail, kick, and mute players. I will be expanding on this
# To make it more dynamic over time. Also, the $player$ part is what gets replaced with the player's name.
mute-vote: 5
   command: /mute $player$ 500
   broadcast: true
kick-vote: 3
   command: /kick $player$
   broadcast: true
jail-vote: 7
   command: /jail $player$ 500
   broadcast: true